version: '3'

services:
  # database
  db:
    image: mysql:5.7
    container_name: employeelist_mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - ./docker/database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/database/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 33306:3306
  # phpMyAdmin
  phpmyadmin:
    container_name: employeelist_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=employeelist_mysql_host
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 10080:80