spring:
  messages:
    basename: 18n/application-messages
    cache-duration: -1
    encoding: UTF-8
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:33306/employee_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
doma:
  dialect: mysql
  data-source-name: jdbc:mysql://localhost:33306/employee_db?user=root&password=root
  exception-sql-log-type: formatted
  jdbc-logger: slf4j